# 数据源配置
spring: 
  datasource: 
    url: jdbc:mysql://localhost:3306/zblog?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true
    username: root
    password: 8721
  
# thymeleaf 配置
  thymeleaf:    cache: false
    prefix: classpath:/WEB-INF/templates/
    suffix: .html
    encoding: utf-8
    mode: html5
    servlet:      content-type: text/html